base_url = "https://www.weskoerber.com"
build_search_index = true
compile_sass = true
generate_feeds = true
feed_filenames = [ "atom.xml" ]
minify_html = true
title = "Wes Koerber"
theme = "apollo"

author = "Wes Koerber"

[markdown.highlighting]
error_on_missing_language = true
theme = "gruvbox-dark-medium"

[extra]
comment = false
custom_css = []
menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/about", url = "/about", weight = 2 }
]
socials = [
    { name = "github", url = "https://github.com/weskoerber", icon = "github" },
    { name = "gitlab", url = "https://gitlab.com/weskoerber", icon = "gitlab" },
    { name = "linkedin", url = "https://www.linkedin.com/in/weskoerber/", icon = "linkedin" },
    { name = "email", url = "mailto:wes@weskoerber.com", icon = "email" },
    { name = "rss", url = "https://www.weskoerber.com/atom.xml", icon = "rss" }
]
theme = "toggle"
toc = true
use_cdn = false

[extra.analytics]
enabled = true

[extra.analytics.goatcounter]
user = "weskoerber"
host = "goatcounter.com"
